In [188]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

In [3]:
obj = pd.Series([4, 7, -5, 3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [9]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [11]:
obj2['a']

-5

In [12]:
obj2['d'] = 6

In [13]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [15]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [16]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [18]:
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [19]:
'b' in obj2

True

In [20]:
'e' in obj2

False

In [21]:
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}

In [22]:
obj3 = pd.Series(sdata)

In [23]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [26]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [27]:
obj4 = pd.Series(sdata, index=states)

In [28]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [30]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [31]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [32]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [33]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [34]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [35]:
obj4.name = 'population'

In [36]:
obj4.index.name = 'state'

In [37]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [38]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [40]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [41]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [43]:
data = {'state' : ['Ohio', 'Ohio', 'Ohio', 'Navada', 'Navada', 'Navada'],
        'year' : [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [45]:
frame = pd.DataFrame(data)

In [46]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Navada  2001  2.4
4  Navada  2002  2.9
5  Navada  2003  3.2

In [47]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Navada  2001  2.4
4  Navada  2002  2.9

In [49]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Navada  2.4
4  2002  Navada  2.9
5  2003  Navada  3.2

In [50]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index=['one', 'two', 'three', 'four', 'five', 'six'])

In [51]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Navada  2.4  NaN
five   2002  Navada  2.9  NaN
six    2003  Navada  3.2  NaN

In [54]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [56]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Navada
five     Navada
six      Navada
Name: state, dtype: object

In [57]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [59]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [60]:
frame2['debt'] = 16.5

In [61]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Navada  2.4  16.5
five   2002  Navada  2.9  16.5
six    2003  Navada  3.2  16.5

In [62]:
frame2['debt'] = np.arange(6.)

In [63]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Navada  2.4   3.0
five   2002  Navada  2.9   4.0
six    2003  Navada  3.2   5.0

In [64]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [65]:
frame2['debt'] = val

In [66]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Navada  2.4  -1.5
five   2002  Navada  2.9  -1.7
six    2003  Navada  3.2   NaN

In [67]:
frame2['eastern'] = frame2.state == 'Ohio'

In [68]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Navada  2.4  -1.5    False
five   2002  Navada  2.9  -1.7    False
six    2003  Navada  3.2   NaN    False

In [69]:
del frame2['eastern']

In [70]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [71]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [72]:
frame3 = pd.DataFrame(pop)

In [73]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [74]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [75]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [77]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [78]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [79]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [80]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [81]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [82]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Navada', 2.4, -1.5],
       [2002, 'Navada', 2.9, -1.7],
       [2003, 'Navada', 3.2, nan]], dtype=object)

In [83]:
obj = pd.Series(range(3), index=['a', 'b', 'c|'])

In [84]:
index = obj.index

In [85]:
index

Index(['a', 'b', 'c|'], dtype='object')

In [86]:
index[1:]

Index(['b', 'c|'], dtype='object')

In [87]:
labels = pd.Index(np.arange(3))

In [88]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [89]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [90]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [91]:
obj2.index is labels

True

In [92]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [94]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [95]:
'Ohio' in frame3.columns

True

In [96]:
2003 in frame3.index

False

In [97]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [98]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [101]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [102]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [105]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [106]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [107]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [108]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [109]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [110]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

In [111]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [112]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [113]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [114]:
states = ['Texas', 'Utah', 'California']

In [115]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [121]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [122]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [123]:
new_obj = obj.drop('c')

In [124]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [125]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [126]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [127]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [129]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [132]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [133]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [134]:
obj.drop('c', inplace=True)

In [135]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [136]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [137]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [138]:
obj['b']

1.0

In [139]:
obj[1]

1.0

In [141]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [142]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [143]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [144]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [145]:
obj['b':'c'] = 5

In [146]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [164]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                     columns=['one', 'two', 'three', 'four'])

In [165]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [166]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [167]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [168]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [169]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [170]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [171]:
data[data < 5] = 0

In [172]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [173]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [174]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [175]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [176]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [178]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [180]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [181]:
ser = pd.Series(np.arange(3.))

In [182]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [183]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [184]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [185]:
ser[:1]

0    0.0
dtype: float64

In [186]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [187]:
ser.iloc[:1]

0    0.0
dtype: float64

In [189]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [190]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [191]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [192]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [193]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [194]:
df1 = pd .DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])

In [195]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [196]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [197]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [198]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [199]:
df1 = pd.DataFrame({'A': [1, 2]})

In [201]:
df2 = pd.DataFrame({'B': [3, 4]})

In [202]:
df1

A
0  1
1  2

In [203]:
df2

B
0  3
1  4

In [205]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [206]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))

In [214]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))

In [215]:
df2.loc[1, 'b'] = np.nan

In [216]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [217]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [218]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [219]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [220]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [221]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [222]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [223]:
arr = np.arange(12.).reshape((3, 4))

In [224]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [225]:
arr[0]

array([0., 1., 2., 3.])

In [226]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [227]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [228]:
series = frame.iloc[0]

In [229]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [230]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [231]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [233]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [235]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [236]:
series3 = frame['d']

In [237]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [238]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [239]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [240]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [241]:
frame

b         d         e
Utah   -0.930245  0.806731 -1.020707
Ohio    1.006959  1.460978 -1.600511
Texas  -1.165215  1.855798 -0.005279
Oregon  0.715400  2.349792 -1.138562

In [242]:
np.abs(frame)

b         d         e
Utah    0.930245  0.806731  1.020707
Ohio    1.006959  1.460978  1.600511
Texas   1.165215  1.855798  0.005279
Oregon  0.715400  2.349792  1.138562

In [243]:
f = lambda x: x.max() - x.min()

In [244]:
frame.apply(f)

b    2.172173
d    1.543061
e    1.595232
dtype: float64

In [245]:
frame.apply(f, axis='columns')

Utah      1.827437
Ohio      3.061489
Texas     3.021013
Oregon    3.488354
dtype: float64

In [248]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [249]:
frame.apply(f)

b         d         e
min -1.165215  0.806731 -1.600511
max  1.006959  2.349792 -0.005279

In [250]:
format = lambda x: '%.2f' % x

In [251]:
frame.applymap(format)

b     d      e
Utah    -0.93  0.81  -1.02
Ohio     1.01  1.46  -1.60
Texas   -1.17  1.86  -0.01
Oregon   0.72  2.35  -1.14

In [252]:
frame['e'].map(format)

Utah      -1.02
Ohio      -1.60
Texas     -0.01
Oregon    -1.14
Name: e, dtype: object

In [2]:
import pandas as pd
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [3]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [5]:
import numpy as np
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                    index=['three', 'one'],
                    columns=['d', 'a', 'b', 'c'])

In [6]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [8]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [10]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [12]:
obj = pd.Series([4, 7, -3, 2])

In [13]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [14]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [15]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [16]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [17]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [18]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [19]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [20]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [21]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [22]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [23]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [25]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                     'c': [-2, 5, 8, -2.5]})

In [26]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [27]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [28]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [29]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [30]:
obj.index.is_unique

False

In [31]:
obj['a']

a    0
a    1
dtype: int64

In [32]:
obj['c']

4

In [33]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [34]:
df

0         1         2
a -0.393757 -0.603757 -1.634618
a -0.707243  1.344358 -0.091061
b -0.681004 -1.694522 -1.453783
b -1.601422  0.499039  0.847611

In [35]:
df.loc['b']

0         1         2
b -0.681004 -1.694522 -1.453783
b -1.601422  0.499039  0.847611

In [36]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                  [np.nan, np.nan], [0.75, -1.3]],
                 index=['a', 'b', 'c', 'd'],
                 columns=['one', 'two'])

In [37]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [38]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [40]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [41]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [42]:
df.idxmax()

one    b
two    d
dtype: object

In [43]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [44]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [45]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [46]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

ModuleNotFoundError: No module named 'pandas_datareader'

In [49]:
import pandas_datareader.data as web

In [53]:
all_data = {ticker: web.get_data_yahoo(ticker)
           for ticker in ['AAAP', 'IBM', 'MSFT', 'GOOG']}
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [54]:
returns = price.pct_change()

In [55]:
returns.tail()

AAAP       IBM      MSFT      GOOG
Date                                          
2020-07-24   0.0 -0.012095 -0.006122 -0.002514
2020-07-27   0.0  0.003339  0.012668  0.012124
2020-07-28   0.0 -0.013787 -0.008977 -0.019514
2020-07-29   0.0  0.006829  0.010098  0.014450
2020-07-30   0.0 -0.019311 -0.000784  0.006196

In [57]:
returns['MSFT'].corr(returns['IBM'])

0.5938112855951989

In [59]:
returns['MSFT'].cov(returns['IBM'])

0.00016683262110809384

In [60]:
returns.MSFT.corr(returns.IBM)

0.5938112855951989

In [61]:
returns.corr()

AAAP       IBM      MSFT      GOOG
AAAP  1.000000  0.031146  0.030471  0.064636
IBM   0.031146  1.000000  0.593811  0.544393
MSFT  0.030471  0.593811  1.000000  0.786260
GOOG  0.064636  0.544393  0.786260  1.000000

In [62]:
returns.cov()

AAAP       IBM      MSFT      GOOG
AAAP  0.001253  0.000018  0.000019  0.000037
IBM   0.000018  0.000260  0.000167  0.000146
MSFT  0.000019  0.000167  0.000304  0.000228
GOOG  0.000037  0.000146  0.000228  0.000277

In [63]:
returns.corrwith(returns.IBM)

AAAP    0.031146
IBM     1.000000
MSFT    0.593811
GOOG    0.544393
dtype: float64

In [64]:
returns.corrwith(volume)

AAAP    0.085903
IBM    -0.103135
MSFT   -0.067223
GOOG   -0.142879
dtype: float64

In [65]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [66]:
uniques = obj.unique()

In [67]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [68]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [69]:
pd.value_counts(obj.values, sort=False)

c    3
a    3
d    1
b    2
dtype: int64

In [71]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [72]:
mask = obj.isin(['b', 'c'])

In [73]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [74]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [75]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [76]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [78]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [79]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})

In [80]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [81]:
result = data.apply(pd.value_counts).fillna(0)

In [82]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0